/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.myproject.aifirstproject;

/**
 *
 * @author Lenovo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        startPanel = new javax.swing.JPanel();
        size8Board = new javax.swing.JRadioButton();
        size4Board = new javax.swing.JRadioButton();
        size5Board = new javax.swing.JRadioButton();
        size6Board = new javax.swing.JRadioButton();
        size7Board = new javax.swing.JRadioButton();
        simAnnealingBTN = new javax.swing.JButton();
        gotoHillClimbingBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startPanel.setBackground(new java.awt.Color(153, 204, 255));
        startPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        size8Board.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(size8Board);
        size8Board.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        size8Board.setText("8x8");
        size8Board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size8BoardActionPerformed(evt);
            }
        });
        startPanel.add(size8Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 60, 30));

        size4Board.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(size4Board);
        size4Board.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        size4Board.setText("4x4");
        size4Board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size4BoardActionPerformed(evt);
            }
        });
        startPanel.add(size4Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 90, 30));

        size5Board.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(size5Board);
        size5Board.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        size5Board.setText("5x5");
        size5Board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size5BoardActionPerformed(evt);
            }
        });
        startPanel.add(size5Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 30));

        size6Board.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(size6Board);
        size6Board.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        size6Board.setText("6x6");
        size6Board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size6BoardActionPerformed(evt);
            }
        });
        startPanel.add(size6Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 60, 30));

        size7Board.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(size7Board);
        size7Board.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        size7Board.setText("7x7");
        size7Board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size7BoardActionPerformed(evt);
            }
        });
        startPanel.add(size7Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 60, 30));

        simAnnealingBTN.setBackground(new java.awt.Color(255, 218, 0));
        simAnnealingBTN.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        simAnnealingBTN.setText("Simulated Annealing");
        simAnnealingBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        simAnnealingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simAnnealingBTNActionPerformed(evt);
            }
        });
        startPanel.add(simAnnealingBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 230, 60));

        gotoHillClimbingBTN.setBackground(new java.awt.Color(255, 218, 0));
        gotoHillClimbingBTN.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        gotoHillClimbingBTN.setText("Hill Climbing");
        gotoHillClimbingBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gotoHillClimbingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoHillClimbingBTNActionPerformed(evt);
            }
        });
        startPanel.add(gotoHillClimbingBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 230, 60));

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 32)); // NOI18N
        jLabel3.setText("N - Queen");
        jLabel3.setOpaque(true);
        startPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 170, 40));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBar(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Please choose the desired board size, then proceed to  \n                      choose the desired algorithm!");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        startPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 630, 120));

        getContentPane().add(startPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void size8BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size8BoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size8BoardActionPerformed

    private void size4BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size4BoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size4BoardActionPerformed

    private void size5BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size5BoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size5BoardActionPerformed

    private void size6BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size6BoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size6BoardActionPerformed

    private void size7BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size7BoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size7BoardActionPerformed

    private void simAnnealingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simAnnealingBTNActionPerformed
        // TODO add your handling code here:
        if(size4Board.isSelected())
        {
            this.toBack();
            SimulatedAnnealingFrame SAF= new SimulatedAnnealingFrame(4);
            SAF.setVisible(true);
            SAF.toFront();
            this.dispose();
        }
        else if(size5Board.isSelected())
        {
            this.toBack();
            SimulatedAnnealingFrame SAF= new SimulatedAnnealingFrame(5);
            SAF.setVisible(true);
            SAF.toFront();
            this.dispose();
        }
        else if(size6Board.isSelected())
        {
            this.toBack();
            SimulatedAnnealingFrame SAF= new SimulatedAnnealingFrame(6);
            SAF.setVisible(true);
            SAF.toFront();
            this.dispose();
        }
        else if(size7Board.isSelected())
        {
            this.toBack();
            SimulatedAnnealingFrame SAF= new SimulatedAnnealingFrame(7);
            SAF.setVisible(true);
            SAF.toFront();
            this.dispose();
        }
        else if(size8Board.isSelected())
        {
            this.toBack();
            SimulatedAnnealingFrame SAF= new SimulatedAnnealingFrame(8);
            SAF.setVisible(true);
            SAF.toFront();
            this.dispose();
        }
    }//GEN-LAST:event_simAnnealingBTNActionPerformed

    private void gotoHillClimbingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoHillClimbingBTNActionPerformed
        // TODO add your handling code here:
        if(size4Board.isSelected())
        {
            this.toBack();
            HillClimbingFrame HCF= new HillClimbingFrame(4);
            HCF.setVisible(true);
            HCF.toFront();
            this.dispose();
        }
        else if(size5Board.isSelected())
        {
            this.toBack();
            HillClimbingFrame HCF= new HillClimbingFrame(5);
            HCF.setVisible(true);
            HCF.toFront();
            this.dispose();
        }
        else if(size6Board.isSelected())
        {
            this.toBack();
            HillClimbingFrame HCF= new HillClimbingFrame(6);
            HCF.setVisible(true);
            HCF.toFront();
            this.dispose();
        }
        else if(size7Board.isSelected())
        {
            this.toBack();
            HillClimbingFrame HCF= new HillClimbingFrame(7);
            HCF.setVisible(true);
            HCF.toFront();
            this.dispose();
        }
        else if(size8Board.isSelected())
        {
            this.toBack();
            HillClimbingFrame HCF= new HillClimbingFrame(8);
            HCF.setVisible(true);
            HCF.toFront();
            this.dispose();
        }
    }//GEN-LAST:event_gotoHillClimbingBTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton gotoHillClimbingBTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton simAnnealingBTN;
    private javax.swing.JRadioButton size4Board;
    private javax.swing.JRadioButton size5Board;
    private javax.swing.JRadioButton size6Board;
    private javax.swing.JRadioButton size7Board;
    private javax.swing.JRadioButton size8Board;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
